Table Country {
  country_id INTEGER [primary key]
  country_name VARCHAR(100) [not null]
}

Table City {
  city_id INTEGER [primary key]
  city_name VARCHAR(100) [not null]
  country_id INTEGER [not null, ref: > Country.country_id]
}

Table Street_address {
  street_address_id INTEGER [primary key]
  street_address VARCHAR(255) [not null]
  postal_code VARCHAR(20) [not null]
}

Table City_Street {
  Primary Key (city_id, street_address_id)
  city_id INTEGER [not null, ref: > City.city_id]
  street_address_id INTEGER [not null, ref: > Street_address.street_address_id]
}

Table School {
  school_id INTEGER [primary key]
  school_name VARCHAR(100)
  street_address_id INTEGER [ref: > Street_address.street_address_id]
}

Table Program {
  program_id INTEGER [primary key]
  program_name VARCHAR(100) [not null]
  description TEXT
}

Table School_Program {
  primary key (school_id, program_id)
  school_id INTEGER [not null, ref: > School.school_id]
  program_id INTEGER [not null, ref: > Program.program_id]
}

Table Class {
    class_id INTEGER [primary key]
    class_name_id INTEGER [ref: > Class_Name.class_name_id]
    program_id INTEGER [ref: > Program.program_id]
    education_manager_id INTEGER [ref: > Education_manager.education_manager_id]
    start_date DATE
    end_date DATE
}

Table Class_Name {
    class_name_id INTEGER [primary key]
    class_name VARCHAR(40) [not null]
}

Table Education_manager {
  education_manager_id INTEGER [primary key]
  first_name VARCHAR(100)
  last_name VARCHAR(100)
  email VARCHAR(100)
  personal_info_id INTEGER [ref: > Personal_info.personal_info_id]
  street_address_id INTEGER [ref: > Street_address.street_address_id]
  is_active BOOLEAN
}

Table Personal_info {
  personal_info_id INTEGER [primary key]
  personal_number VARCHAR(20) [not null, unique]
  phone_number VARCHAR(20)
}

Table Course {
  course_id INTEGER [primary key]
  course_name VARCHAR(100) [not null]
  credits INTEGER [not null]
  description TEXT
  start_date DATE
  end_date DATE
  is_standalone BOOLEAN
}

Table Program_Course {
  primary key (program_id, course_id)
  program_id INTEGER [not null, ref: > Program.program_id]
  course_id INTEGER [not null, ref: > Course.course_id]
}

Table Teacher {
  teacher_id INTEGER [primary key]
  first_name VARCHAR(100) [not null]
  last_name VARCHAR(100) [not null]
  email VARCHAR(100) [not null]
  hire_date DATE
  is_active BOOLEAN 
  personal_info_id INTEGER [ref: > Personal_info.personal_info_id]
  street_address_id INTEGER [ref: > Street_address.street_address_id]
}

Table Course_Teacher {
  primary key (course_id, teacher_id) 
  course_id INTEGER [not null, ref: > Course.course_id]
  teacher_id INTEGER [not null, ref: > Teacher.teacher_id]
}

Table Company {
  organization_number VARCHAR(50) [primary key]
  company_name VARCHAR(100) [not null]
  has_f_tax BOOLEAN [not null]
  street_address_id INTEGER [not null, ref: > Street_address.street_address_id]
}

Table Consult {
  consult_id INTEGER [primary key]
  organization_number VARCHAR(50) [not null, ref: > Company.organization_number]
  hourly_rate DECIMAL(10, 2) [not null]
  full_name VARCHAR(100) [not null]
  is_active BOOLEAN
}

Table Course_Consult {
  primary key (course_id, consult_id)
  course_id INTEGER [not null, ref: > Course.course_id]
  consult_id INTEGER [not null, ref: > Consult.consult_id]
}

Table Student {
  student_id INTEGER [primary key]
  first_name VARCHAR(100) [not null]
  last_name VARCHAR(100) [not null]
  email VARCHAR(100) [not null]
  street_address_id INTEGER [ref: > Street_address.street_address_id]
  class_id INTEGER [ref: > Class.class_id]
  personal_info_id INTEGER [ref: > Personal_info.personal_info_id]
}

Table Student_Course {
  primary key (student_id, course_id)
  student_id INTEGER [not null, ref: > Student.student_id]
  course_id INTEGER [not null, ref: > Course.course_id]
  enrollment_date DATE
  completion_date DATE
}

